#!/usr/bin/env bash
#
# Generate moved.tf for the count -> for_each migration of path integrations in
# terraform-aws-opinionated-api-gateway (v2.0.0).
#
# Reads the current Terraform state for the four count-indexed submodules:
#   <module-address>.module.s3_integrations[N]
#   <module-address>.module.sns_integrations[N]
#   <module-address>.module.proxy_integrations[N]
#   <module-address>.module.lambda_integrations[N]
# and emits one `moved` block per instance, pointing it at the new
# path-keyed address. Because the count is on the module call itself, moving
# the module instance moves its entire resource subtree - there is no need to
# enumerate the resources inside it individually.
#
# Run from the consumer root module (the directory containing the
# `module "..." { source = ".../opinionated-api-gateway/aws" ... }` block),
# against state from BEFORE the module version is bumped to 2.0.0 - the old
# count-indexed addresses must still exist in state for this to find them.
#
# Usage:
#   scripts/generate-path-moves.sh <module-address> [out-file]
#
# After applying the resulting moved.tf, delete it (moved blocks are one-shot).

set -euo pipefail

usage() {
  sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
  exit "${1:-2}"
}

case "${1:-}" in
  -h|--help) usage 0 ;;
esac

MODULE_ADDR="${1:?missing module address (e.g. module.internal_gateway). See --help.}"
OUT_FILE="${2:-}"

# Strip trailing dot if user passed "module.internal_gateway."
MODULE_ADDR="${MODULE_ADDR%.}"

if ! command -v terraform >/dev/null 2>&1; then
  echo "error: terraform not found on PATH" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq not found on PATH" >&2
  exit 1
fi

# The submodule name -> the one resource in it that always carries the full
# computed `path` attribute, regardless of nesting depth or optional siblings.
# See UPGRADING.md for why each of these was chosen.
TERMINALS='{
  "s3_integrations":     {"type": "aws_api_gateway_resource", "name": "item"},
  "sns_integrations":    {"type": "aws_api_gateway_resource", "name": "path_root"},
  "proxy_integrations":  {"type": "aws_api_gateway_resource", "name": "proxy"},
  "lambda_integrations": {"type": "aws_api_gateway_resource", "name": "proxy"}
}'

# Escape regex metacharacters in the module address (it will contain at least
# one literal ".").
ESCAPED_ADDR="$(printf '%s' "$MODULE_ADDR" | sed -e 's/[.[\*^$()+?{}|]/\\&/g')"
MATCH_RE="^${ESCAPED_ADDR}\\.module\\.(s3_integrations|sns_integrations|proxy_integrations|lambda_integrations)\\[[0-9]+\\]\$"
CAPTURE_RE="^${ESCAPED_ADDR}\\.module\\.(?<mod>s3_integrations|sns_integrations|proxy_integrations|lambda_integrations)\\[(?<idx>[0-9]+)\\]\$"

STATE_JSON="$(terraform show -json)"

if [[ -z "$STATE_JSON" || "$STATE_JSON" == "null" ]]; then
  echo "error: 'terraform show -json' returned no state - is this run from an initialized root module with existing state?" >&2
  exit 1
fi

ROWS="$(jq -r \
  --arg matchRe "$MATCH_RE" \
  --arg captureRe "$CAPTURE_RE" \
  --argjson terminals "$TERMINALS" \
  '
  [.. | objects | select(has("address") and has("resources"))]
  | map(select(.address | test($matchRe)))
  | map(
      . as $m
      | ($m.address | capture($captureRe)) as $c
      | ($terminals[$c.mod]) as $t
      | ($m.resources | map(select(.type == $t.type and .name == $t.name))) as $matches
      | ($matches[0].values.path // "MISSING") as $p
      | [$c.mod, $c.idx, $p]
    )
  | .[]
  | @tsv
  ' <<< "$STATE_JSON")"

if [[ -z "$ROWS" ]]; then
  echo "# No count-indexed submodule instances found under ${MODULE_ADDR}" >&2
  echo "# (nothing to migrate - either already migrated, or this module has no mappings of any type)" >&2
  exit 0
fi

# Validate every row up front - fail before writing anything (including partial
# appends to an existing OUT_FILE) if any instance's path can't be recovered.
while IFS=$'\t' read -r mod idx path_attr; do
  if [[ "$path_attr" == "MISSING" ]]; then
    echo "error: could not recover a path for ${MODULE_ADDR}.module.${mod}[${idx}]" >&2
    echo "       (its terminal aws_api_gateway_resource is missing - this is expected only for a" >&2
    echo "       root-level mapping with no path segment, e.g. lambda type with path \"/\"; add a" >&2
    echo "       moved block for that instance by hand, see UPGRADING.md)" >&2
    exit 1
  fi
done <<< "$ROWS"

emit() {
  cat <<EOF
# Generated by scripts/generate-path-moves.sh
# Module: ${MODULE_ADDR}
#
# Apply once, then delete this file.

EOF

  while IFS=$'\t' read -r mod idx path_attr; do
    # path_attr is the AWS-computed full path, e.g. "/institution-created" -
    # strip the leading "/" to match the trim(path, "/") key used in paths.tf.
    key="${path_attr#/}"

    cat <<EOF
moved {
  from = ${MODULE_ADDR}.module.${mod}[${idx}]
  to   = ${MODULE_ADDR}.module.${mod}["${key}"]
}

EOF
  done <<< "$ROWS"
}

if [[ -n "$OUT_FILE" ]]; then
  emit >> "$OUT_FILE"
  echo "wrote/appended $OUT_FILE" >&2
else
  emit
fi
